# Generated by Django 5.1.2 on 2024-10-09 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minddistrict_connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minddistrict_connect.platformconfig'),
        ),
    ]
